// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.2
// source: api_options.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type APISourceType int32

const (
	APISourceType_SOURCE_BOTH   APISourceType = 0
	APISourceType_SOURCE_SERVER APISourceType = 1
	APISourceType_SOURCE_CLIENT APISourceType = 2
)

// Enum value maps for APISourceType.
var (
	APISourceType_name = map[int32]string{
		0: "SOURCE_BOTH",
		1: "SOURCE_SERVER",
		2: "SOURCE_CLIENT",
	}
	APISourceType_value = map[string]int32{
		"SOURCE_BOTH":   0,
		"SOURCE_SERVER": 1,
		"SOURCE_CLIENT": 2,
	}
)

func (x APISourceType) Enum() *APISourceType {
	p := new(APISourceType)
	*p = x
	return p
}

func (x APISourceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (APISourceType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_options_proto_enumTypes[0].Descriptor()
}

func (APISourceType) Type() protoreflect.EnumType {
	return &file_api_options_proto_enumTypes[0]
}

func (x APISourceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *APISourceType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = APISourceType(num)
	return nil
}

// Deprecated: Use APISourceType.Descriptor instead.
func (APISourceType) EnumDescriptor() ([]byte, []int) {
	return file_api_options_proto_rawDescGZIP(), []int{0}
}

type Void struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Void) Reset() {
	*x = Void{}
	mi := &file_api_options_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Void) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Void) ProtoMessage() {}

func (x *Void) ProtoReflect() protoreflect.Message {
	mi := &file_api_options_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Void.ProtoReflect.Descriptor instead.
func (*Void) Descriptor() ([]byte, []int) {
	return file_api_options_proto_rawDescGZIP(), []int{0}
}

var file_api_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         1038,
		Name:          "needs_setup_connection",
		Tag:           "varint,1038,opt,name=needs_setup_connection,def=1",
		Filename:      "api_options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         1039,
		Name:          "needs_authentication",
		Tag:           "varint,1039,opt,name=needs_authentication,def=1",
		Filename:      "api_options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*uint32)(nil),
		Field:         1036,
		Name:          "id",
		Tag:           "varint,1036,opt,name=id,def=0",
		Filename:      "api_options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*APISourceType)(nil),
		Field:         1037,
		Name:          "source",
		Tag:           "varint,1037,opt,name=source,enum=APISourceType,def=0",
		Filename:      "api_options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         1038,
		Name:          "ifdef",
		Tag:           "bytes,1038,opt,name=ifdef",
		Filename:      "api_options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         1039,
		Name:          "log",
		Tag:           "varint,1039,opt,name=log,def=1",
		Filename:      "api_options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         1040,
		Name:          "no_delay",
		Tag:           "varint,1040,opt,name=no_delay,def=0",
		Filename:      "api_options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         1041,
		Name:          "base_class",
		Tag:           "bytes,1041,opt,name=base_class",
		Filename:      "api_options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         1042,
		Name:          "inline_encode",
		Tag:           "varint,1042,opt,name=inline_encode,def=0",
		Filename:      "api_options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         1043,
		Name:          "speed_optimized",
		Tag:           "varint,1043,opt,name=speed_optimized,def=0",
		Filename:      "api_options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         1042,
		Name:          "field_ifdef",
		Tag:           "bytes,1042,opt,name=field_ifdef",
		Filename:      "api_options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*uint32)(nil),
		Field:         50007,
		Name:          "fixed_array_size",
		Tag:           "varint,50007,opt,name=fixed_array_size",
		Filename:      "api_options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50009,
		Name:          "fixed_array_skip_zero",
		Tag:           "varint,50009,opt,name=fixed_array_skip_zero,def=0",
		Filename:      "api_options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50010,
		Name:          "fixed_array_size_define",
		Tag:           "bytes,50010,opt,name=fixed_array_size_define",
		Filename:      "api_options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50011,
		Name:          "fixed_array_with_length_define",
		Tag:           "bytes,50011,opt,name=fixed_array_with_length_define",
		Filename:      "api_options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50012,
		Name:          "pointer_to_buffer",
		Tag:           "varint,50012,opt,name=pointer_to_buffer,def=0",
		Filename:      "api_options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50001,
		Name:          "container_pointer",
		Tag:           "bytes,50001,opt,name=container_pointer",
		Filename:      "api_options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50013,
		Name:          "fixed_vector",
		Tag:           "varint,50013,opt,name=fixed_vector,def=0",
		Filename:      "api_options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50014,
		Name:          "container_pointer_no_template",
		Tag:           "bytes,50014,opt,name=container_pointer_no_template",
		Filename:      "api_options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50015,
		Name:          "packed_buffer",
		Tag:           "varint,50015,opt,name=packed_buffer,def=0",
		Filename:      "api_options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50016,
		Name:          "force",
		Tag:           "varint,50016,opt,name=force,def=0",
		Filename:      "api_options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*uint32)(nil),
		Field:         50017,
		Name:          "max_value",
		Tag:           "varint,50017,opt,name=max_value",
		Filename:      "api_options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*uint32)(nil),
		Field:         50018,
		Name:          "max_data_length",
		Tag:           "varint,50018,opt,name=max_data_length",
		Filename:      "api_options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50019,
		Name:          "mac_address",
		Tag:           "varint,50019,opt,name=mac_address,def=0",
		Filename:      "api_options.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional bool needs_setup_connection = 1038;
	E_NeedsSetupConnection = &file_api_options_proto_extTypes[0]
	// optional bool needs_authentication = 1039;
	E_NeedsAuthentication = &file_api_options_proto_extTypes[1]
)

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional uint32 id = 1036;
	E_Id = &file_api_options_proto_extTypes[2]
	// optional APISourceType source = 1037;
	E_Source = &file_api_options_proto_extTypes[3]
	// optional string ifdef = 1038;
	E_Ifdef = &file_api_options_proto_extTypes[4]
	// optional bool log = 1039;
	E_Log = &file_api_options_proto_extTypes[5]
	// optional bool no_delay = 1040;
	E_NoDelay = &file_api_options_proto_extTypes[6]
	// optional string base_class = 1041;
	E_BaseClass = &file_api_options_proto_extTypes[7]
	// optional bool inline_encode = 1042;
	E_InlineEncode = &file_api_options_proto_extTypes[8]
	// optional bool speed_optimized = 1043;
	E_SpeedOptimized = &file_api_options_proto_extTypes[9]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional string field_ifdef = 1042;
	E_FieldIfdef = &file_api_options_proto_extTypes[10]
	// optional uint32 fixed_array_size = 50007;
	E_FixedArraySize = &file_api_options_proto_extTypes[11]
	// optional bool fixed_array_skip_zero = 50009;
	E_FixedArraySkipZero = &file_api_options_proto_extTypes[12]
	// optional string fixed_array_size_define = 50010;
	E_FixedArraySizeDefine = &file_api_options_proto_extTypes[13]
	// optional string fixed_array_with_length_define = 50011;
	E_FixedArrayWithLengthDefine = &file_api_options_proto_extTypes[14]
	// pointer_to_buffer: Use pointer instead of array for fixed-size byte fields
	// When set, the field will be declared as a pointer (const uint8_t *data)
	// instead of an array (uint8_t data[N]). This allows zero-copy on decode
	// by pointing directly to the protobuf buffer. The buffer must remain valid
	// until the message is processed (which is guaranteed for stack-allocated messages).
	//
	// optional bool pointer_to_buffer = 50012;
	E_PointerToBuffer = &file_api_options_proto_extTypes[15]
	// container_pointer: Zero-copy optimization for repeated fields.
	//
	// When container_pointer is set on a repeated field, the generated message will
	// store a pointer to an existing container instead of copying the data into the
	// message's own repeated field. This eliminates heap allocations and improves performance.
	//
	// Requirements for safe usage:
	// 1. The source container must remain valid until the message is encoded
	// 2. Messages must be encoded immediately (which ESPHome does by default)
	// 3. The container type must match the field type exactly
	//
	// Supported container types:
	// - "std::vector<T>" for most repeated fields
	// - "std::set<T>" for unique/sorted data
	// - Full type specification required for enums (e.g., "std::set<climate::ClimateMode>")
	//
	// Example usage in .proto file:
	//
	//	repeated string supported_modes = 12 [(container_pointer) = "std::set"];
	//	repeated ColorMode color_modes = 13 [(container_pointer) = "std::set<light::ColorMode>"];
	//
	// The corresponding C++ code must provide const reference access to a container
	// that matches the specified type and remains valid during message encoding.
	// This is typically done through methods returning const T& or special accessor
	// methods like get_options() or supported_modes_for_api_().
	//
	// optional string container_pointer = 50001;
	E_ContainerPointer = &file_api_options_proto_extTypes[16]
	// fixed_vector: Use FixedVector instead of std::vector for repeated fields
	// When set, the repeated field will use FixedVector<T> which requires calling
	// init(size) before adding elements. This eliminates std::vector template overhead
	// and is ideal when the exact size is known before populating the array.
	//
	// optional bool fixed_vector = 50013;
	E_FixedVector = &file_api_options_proto_extTypes[17]
	// container_pointer_no_template: Use a non-template container type for repeated fields
	// Similar to container_pointer, but for containers that don't take template parameters.
	// The container type is used as-is without appending element type.
	// The container must have:
	// - begin() and end() methods returning iterators
	// - empty() method
	// Example: [(container_pointer_no_template) = "light::ColorModeMask"]
	//
	//	generates: const light::ColorModeMask *supported_color_modes{};
	//
	// optional string container_pointer_no_template = 50014;
	E_ContainerPointerNoTemplate = &file_api_options_proto_extTypes[18]
	// packed_buffer: Expose raw packed buffer instead of decoding into container
	// When set on a packed repeated field, the generated code stores a pointer
	// to the raw protobuf buffer instead of decoding values. This enables
	// zero-copy passthrough when the consumer can decode on-demand.
	// The field must be a packed repeated field (packed=true).
	// Generates three fields:
	//   - const uint8_t *<field>_data_{nullptr};
	//   - uint16_t <field>_length_{0};
	//   - uint16_t <field>_count_{0};
	//
	// optional bool packed_buffer = 50015;
	E_PackedBuffer = &file_api_options_proto_extTypes[19]
	// force: Always encode this field, even when its value equals the proto3 default.
	// Skips the zero/empty check in calculate_size() and encode(), using the _force
	// variant of the calc_ method. Use on fields that are almost always non-default
	// to eliminate dead branches on hot paths.
	//
	// optional bool force = 50016;
	E_Force = &file_api_options_proto_extTypes[20]
	// max_value: Maximum value a field can have.
	// When max_value < 128, the code generator emits constant-size calculations
	// and direct byte writes instead of varint branching, since the encoded varint
	// is guaranteed to be 1 byte.
	//
	// optional uint32 max_value = 50017;
	E_MaxValue = &file_api_options_proto_extTypes[21]
	// max_data_length: Maximum length of a string or bytes field.
	// When max_data_length < 128, the code generator emits constant-size
	// length varint calculations and direct byte writes, since the length
	// varint is guaranteed to be 1 byte.
	//
	// optional uint32 max_data_length = 50018;
	E_MaxDataLength = &file_api_options_proto_extTypes[22]
	// mac_address: Field is a 48-bit MAC address stored in a uint64.
	// Emits encode_varint_raw_48bit which has a 7-byte fast path that avoids
	// the per-byte loop when the upper bits are non-zero (the common case
	// for real MAC addresses, since OUIs occupy the top 24 bits).
	//
	// optional bool mac_address = 50019;
	E_MacAddress = &file_api_options_proto_extTypes[23]
)

var File_api_options_proto protoreflect.FileDescriptor

const file_api_options_proto_rawDesc = "" +
	"\n" +
	"\x11api_options.proto\x1a google/protobuf/descriptor.proto\"\x06\n" +
	"\x04void*F\n" +
	"\rAPISourceType\x12\x0f\n" +
	"\vSOURCE_BOTH\x10\x00\x12\x11\n" +
	"\rSOURCE_SERVER\x10\x01\x12\x11\n" +
	"\rSOURCE_CLIENT\x10\x02:[\n" +
	"\x16needs_setup_connection\x12\x1e.google.protobuf.MethodOptions\x18\x8e\b \x01(\b:\x04trueR\x14needsSetupConnection:X\n" +
	"\x14needs_authentication\x12\x1e.google.protobuf.MethodOptions\x18\x8f\b \x01(\b:\x04trueR\x13needsAuthentication:3\n" +
	"\x02id\x12\x1f.google.protobuf.MessageOptions\x18\x8c\b \x01(\r:\x010R\x02id:U\n" +
	"\x06source\x12\x1f.google.protobuf.MessageOptions\x18\x8d\b \x01(\x0e2\x0e.APISourceType:\vSOURCE_BOTHR\x06source:6\n" +
	"\x05ifdef\x12\x1f.google.protobuf.MessageOptions\x18\x8e\b \x01(\tR\x05ifdef:8\n" +
	"\x03log\x12\x1f.google.protobuf.MessageOptions\x18\x8f\b \x01(\b:\x04trueR\x03log:B\n" +
	"\bno_delay\x12\x1f.google.protobuf.MessageOptions\x18\x90\b \x01(\b:\x05falseR\anoDelay:?\n" +
	"\n" +
	"base_class\x12\x1f.google.protobuf.MessageOptions\x18\x91\b \x01(\tR\tbaseClass:L\n" +
	"\rinline_encode\x12\x1f.google.protobuf.MessageOptions\x18\x92\b \x01(\b:\x05falseR\finlineEncode:P\n" +
	"\x0fspeed_optimized\x12\x1f.google.protobuf.MessageOptions\x18\x93\b \x01(\b:\x05falseR\x0espeedOptimized:?\n" +
	"\vfield_ifdef\x12\x1d.google.protobuf.FieldOptions\x18\x92\b \x01(\tR\n" +
	"fieldIfdef:I\n" +
	"\x10fixed_array_size\x12\x1d.google.protobuf.FieldOptions\x18׆\x03 \x01(\rR\x0efixedArraySize:Y\n" +
	"\x15fixed_array_skip_zero\x12\x1d.google.protobuf.FieldOptions\x18ن\x03 \x01(\b:\x05falseR\x12fixedArraySkipZero:V\n" +
	"\x17fixed_array_size_define\x12\x1d.google.protobuf.FieldOptions\x18چ\x03 \x01(\tR\x14fixedArraySizeDefine:c\n" +
	"\x1efixed_array_with_length_define\x12\x1d.google.protobuf.FieldOptions\x18ۆ\x03 \x01(\tR\x1afixedArrayWithLengthDefine:R\n" +
	"\x11pointer_to_buffer\x12\x1d.google.protobuf.FieldOptions\x18܆\x03 \x01(\b:\x05falseR\x0fpointerToBuffer:L\n" +
	"\x11container_pointer\x12\x1d.google.protobuf.FieldOptions\x18ц\x03 \x01(\tR\x10containerPointer:I\n" +
	"\ffixed_vector\x12\x1d.google.protobuf.FieldOptions\x18݆\x03 \x01(\b:\x05falseR\vfixedVector:b\n" +
	"\x1dcontainer_pointer_no_template\x12\x1d.google.protobuf.FieldOptions\x18ކ\x03 \x01(\tR\x1acontainerPointerNoTemplate:K\n" +
	"\rpacked_buffer\x12\x1d.google.protobuf.FieldOptions\x18߆\x03 \x01(\b:\x05falseR\fpackedBuffer:<\n" +
	"\x05force\x12\x1d.google.protobuf.FieldOptions\x18\xe0\x86\x03 \x01(\b:\x05falseR\x05force:<\n" +
	"\tmax_value\x12\x1d.google.protobuf.FieldOptions\x18\xe1\x86\x03 \x01(\rR\bmaxValue:G\n" +
	"\x0fmax_data_length\x12\x1d.google.protobuf.FieldOptions\x18\xe2\x86\x03 \x01(\rR\rmaxDataLength:G\n" +
	"\vmac_address\x12\x1d.google.protobuf.FieldOptions\x18\xe3\x86\x03 \x01(\b:\x05falseR\n" +
	"macAddress"

var (
	file_api_options_proto_rawDescOnce sync.Once
	file_api_options_proto_rawDescData []byte
)

func file_api_options_proto_rawDescGZIP() []byte {
	file_api_options_proto_rawDescOnce.Do(func() {
		file_api_options_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_options_proto_rawDesc), len(file_api_options_proto_rawDesc)))
	})
	return file_api_options_proto_rawDescData
}

var file_api_options_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_options_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_options_proto_goTypes = []any{
	(APISourceType)(0),                  // 0: APISourceType
	(*Void)(nil),                        // 1: void
	(*descriptorpb.MethodOptions)(nil),  // 2: google.protobuf.MethodOptions
	(*descriptorpb.MessageOptions)(nil), // 3: google.protobuf.MessageOptions
	(*descriptorpb.FieldOptions)(nil),   // 4: google.protobuf.FieldOptions
}
var file_api_options_proto_depIdxs = []int32{
	2,  // 0: needs_setup_connection:extendee -> google.protobuf.MethodOptions
	2,  // 1: needs_authentication:extendee -> google.protobuf.MethodOptions
	3,  // 2: id:extendee -> google.protobuf.MessageOptions
	3,  // 3: source:extendee -> google.protobuf.MessageOptions
	3,  // 4: ifdef:extendee -> google.protobuf.MessageOptions
	3,  // 5: log:extendee -> google.protobuf.MessageOptions
	3,  // 6: no_delay:extendee -> google.protobuf.MessageOptions
	3,  // 7: base_class:extendee -> google.protobuf.MessageOptions
	3,  // 8: inline_encode:extendee -> google.protobuf.MessageOptions
	3,  // 9: speed_optimized:extendee -> google.protobuf.MessageOptions
	4,  // 10: field_ifdef:extendee -> google.protobuf.FieldOptions
	4,  // 11: fixed_array_size:extendee -> google.protobuf.FieldOptions
	4,  // 12: fixed_array_skip_zero:extendee -> google.protobuf.FieldOptions
	4,  // 13: fixed_array_size_define:extendee -> google.protobuf.FieldOptions
	4,  // 14: fixed_array_with_length_define:extendee -> google.protobuf.FieldOptions
	4,  // 15: pointer_to_buffer:extendee -> google.protobuf.FieldOptions
	4,  // 16: container_pointer:extendee -> google.protobuf.FieldOptions
	4,  // 17: fixed_vector:extendee -> google.protobuf.FieldOptions
	4,  // 18: container_pointer_no_template:extendee -> google.protobuf.FieldOptions
	4,  // 19: packed_buffer:extendee -> google.protobuf.FieldOptions
	4,  // 20: force:extendee -> google.protobuf.FieldOptions
	4,  // 21: max_value:extendee -> google.protobuf.FieldOptions
	4,  // 22: max_data_length:extendee -> google.protobuf.FieldOptions
	4,  // 23: mac_address:extendee -> google.protobuf.FieldOptions
	0,  // 24: source:type_name -> APISourceType
	25, // [25:25] is the sub-list for method output_type
	25, // [25:25] is the sub-list for method input_type
	24, // [24:25] is the sub-list for extension type_name
	0,  // [0:24] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_api_options_proto_init() }
func file_api_options_proto_init() {
	if File_api_options_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_options_proto_rawDesc), len(file_api_options_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 24,
			NumServices:   0,
		},
		GoTypes:           file_api_options_proto_goTypes,
		DependencyIndexes: file_api_options_proto_depIdxs,
		EnumInfos:         file_api_options_proto_enumTypes,
		MessageInfos:      file_api_options_proto_msgTypes,
		ExtensionInfos:    file_api_options_proto_extTypes,
	}.Build()
	File_api_options_proto = out.File
	file_api_options_proto_goTypes = nil
	file_api_options_proto_depIdxs = nil
}
